### ISSUE TITLE
Could you give some more instruction in details?

### ISSUE THREAD

**Issue by archonwang** [luciof55/plus_gantt#2]
@luciof55 
Could you give some more instruction in details?
I have confused with Readme.md and How to config the plugin to use it correctly? 
Thanks.

**Comment by luciof55** [comment]
Hi @archonwang, 

I updated Readme.md with some explanations. Also i am working on the Wiki pages to improve the documentation.

Please feel free to make any questions.

Regards.

**Comment by archonwang** [comment]
@luciof55 
Thanks. I will try it later.
