### ISSUE TITLE
No "Plus Gantt" item menu

### ISSUE THREAD

**Issue by mvidelgauz** [luciof55/plus_gantt#6]
Hello,
I performed installation, enabled "Plusgantt" in a project's "Modules" page, but no "Plus Gantt" item menu appeared

EDIT: It appeared after I enabled "Plusgantt" in "Administration"-"Roles and permissions". I think it's worth updating instructions

**Comment by luciof55** [comment]
Hi @mvidelgauz.

It is true. Although those explanation is part of redmine plugin configuration, i will add this to installations notes. Thanks in advance.

Regards,

**Comment by mvidelgauz** [comment]
Thank you @luciof55 ,
that's right - I had to carefully read whole redmine plugin configuration , so adding this to each individual plugin instruction is just a bonus for lazy people )))
