### ISSUE TITLE
500 error in redmine 3.4.3 

### ISSUE THREAD

**Issue by aozhi2nd** [luciof55/plus_gantt#8]
```
Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.0
  advanced_roadmap               0.11.0
  gantt_extension                0.2
  plus_gantt                     0.0.7
  projects_tree_view             0.0.9
  redmine__select2               1.1.0
  redmine_banner                 0.1.2
  redmine_base_deface            0.0.1
  redmine_base_stimulusjs        0.9.0
  redmine_category_tree          0.0.7
  redmine_checklists             3.1.10
  redmine_ckeditor               1.1.5
  redmine_dmsf                   1.6.0
  redmine_favourite_projects     0.9.1
  redmine_image_clipboard_paste  3.3.0
  redmine_issue_badge            0.0.6
  redmine_issue_templates        0.1.8
  redmine_lightbox2              0.4.3
  redmine_my_page                0.1.13
  redmine_per_project_formatting 0.0.4
  redmine_pivot_table            0.0.5
  redmine_questions              0.0.7
  redmine_work_time              0.3.4
  redmine_xlsx_format_issue_exporter 0.1.5
  sidebar_hide                   0.0.8
```

```
ActionView::Template::Error (undefined method `link_to_content_update' for #<#<Class:0x00007feb87dc0418>:0x00007feb876f37c0>
Did you mean?  link_to_next_page):
    58: </fieldset>
    59: 
    60: <div class="contextual">
    61:   <%= gantt_zoom_link(@plusgantt, :in) %>
    62:   <%= gantt_zoom_link(@plusgantt, :out) %>
    63: </div>
    64: </p>
  plugins/plus_gantt/app/helpers/plusgantt_helper.rb:7:in `gantt_zoom_link'
  plugins/plus_gantt/app/views/plusgantt/show.html.erb:61:in `block in _4f02717bb4f20494c9d0238e696c8cdb'
  plugins/plus_gantt/app/views/plusgantt/show.html.erb:11:in `_4f02717bb4f20494c9d0238e696c8cdb'
  plugins/plus_gantt/app/controllers/plusgantt_controller.rb:28:in `block (2 levels) in show'
  plugins/plus_gantt/app/controllers/plusgantt_controller.rb:27:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by alidhaey** [comment]
The same error in version 3.4.4 when show cronograpth

Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.4.3-p205 (2017-12-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  plus_gantt                     0.0.7



Started GET "/issues/plusgantt/show?project_id=pr-test-001" for 192.168.1.35 at 2018-02-25 12:35:46 +0100
Processing by PlusganttController#show as HTML
  Parameters: {"project_id"=>"pr-test-001"}
  Current user: admin (id=1)
  Rendered queries/_filters.html.erb (12.2ms)
  Rendered plugins/plus_gantt/app/views/plusgantt/show.html.erb within layouts/base (97.9ms)
Completed 500 Internal Server Error in 125ms (ActiveRecord: 10.4ms)

ActionView::Template::Error (undefined method `link_to_content_update' for #<#<Class:0x00007fad1d9922e0>:0x00007fad1dde42f8>
Did you mean?  link_to_function):
    59: 
    60: <div class="contextual">
    61:   <%= gantt_zoom_link(@plusgantt, :in) %>
    62:   <%= gantt_zoom_link(@plusgantt, :out) %>
    63: </div>
    64: </p>
    65: <% end %>
  plugins/plus_gantt/app/helpers/plusgantt_helper.rb:16:in `gantt_zoom_link'
  plugins/plus_gantt/app/views/plusgantt/show.html.erb:62:in `block in _plugins_plus_gantt_app_views_plusgantt_show_html_erb__4284082112177738117_70190751255600'
  plugins/plus_gantt/app/views/plusgantt/show.html.erb:11:in `_plugins_plus_gantt_app_views_plusgantt_show_html_erb__4284082112177738117_70190751255600'
  plugins/plus_gantt/app/controllers/plusgantt_controller.rb:28:in `block (2 levels) in show'
  plugins/plus_gantt/app/controllers/plusgantt_controller.rb:27:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by luciof55** [comment]
Hi Gessel.

Resolved, please verify. Thanks in advance.

Regards.
