### ISSUE TITLE
git address is "not found"

### ISSUE THREAD

**Issue by gessel** [luciof55/plus_gantt#9]
The pull request should be: 

git clone https://github.com/luciof55/plus_gantt.git

And you might consider adding:

 cd ..
 bundle exec rake redmine:plugins RAILS_ENV=production
 touch tmp/restart.txt

**Comment by luciof55** [comment]
Hi Gessel.

Resolved, please verify. Thanks in advance.

Regards.

**Comment by gessel** [comment]
Thanks!  :)  (and thanks for the very helpful code)
